# 3.1 넘파이 배열

### Numpy Array

In [1]:
# 리스트와 넘파이 어레이 속도 비교
import numpy as np
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]

### 매직 명령어
셀이 돌아가는 시간을 알려줌
```
%%time
```
I think that you want to put each magic section in its own cell. So any line that starts with % should be the beginning of a new input cell.

In [2]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 150 ms


In [4]:
%%time
for i in range(100):
    np.sum(np_arr)

Wall time: 5 ms


### Matrix 연산
```
y = a * x + b
```
Matrix is w * x
```
y = w (Weight) * x + b (Bias)
```

### 1차원 배열 만들기

In [15]:
al = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
al

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
type(al)

numpy.ndarray

In [17]:
al.shape

(10,)

### 벡터화 연산

배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산(vectorized operation)을 지원한다.

In [18]:
ar = [2 * i for i in range(1, 11)]
ar

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [22]:
2 * ar

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [23]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [24]:
2 * a + b

array([12, 24, 36])

In [25]:
 a == 2

array([False,  True, False])

In [26]:
b > 15

array([False,  True,  True])

In [29]:
(a == 2) & (b > 15)

array([False,  True, False])

### 2차원 배열 만들기

ndarray 는 N-dimensional Array의 약자이다. 이름 그대로 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원한다. 2차원 배열은 행렬(matrix)이라고 하는데 행렬에서는 가로줄을 행(row)이라고 하고 세로줄을 열(column)이라고 부른다.

In [40]:
c = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
# 행의 갯수, 열의 갯수
c.shape

(2, 3)

In [42]:
# 행의 갯수, 열의 갯수
len(c), len(c[0])

(2, 3)

### 연습 문제 1
넘파이를 사용하여 다음과 같은 행렬을 만든다.
```
10 20 30 40
50 60 70 80
```

In [53]:
# import numpy as np
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [52]:
a.shape

(2, 4)

In [55]:
a = np.arange(10, 90, 10).reshape(2, -1)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 3차원 배열 만들기

In [59]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

### 배열의 차원과 크기 알아내기

배열의 차원 및 크기를 구하는 더 간단한 방법은 배열의 ndim 속성과 shape 속성을 이용하는 것이다. ndim 속성은 배열의 차원, shape 속성은 배열의 크기를 반환한다.

In [69]:
a = np.array([1, 2, 3])
c = np.array([[0, 1, 2], [3, 4, 5]])

In [75]:
# 배열의 차원, 크기
a.ndim, a.shape

(1, (3,))

In [77]:
# 배열의 차원, 크기
c.ndim, c.shape

(2, (2, 3))

### 배열 인덱싱

In [91]:
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [90]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a[1, 0]

3

### 배열 슬라이싱

In [93]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [94]:
# 모든행[:] 에서 1열 ~ 3열[1:3] 인덱싱
a[:, 1:3]

array([[1, 2],
       [5, 6]])

### 연습문제 3

1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```

In [121]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [122]:
x % 3 == 0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [123]:
x % 4 == 1

array([ True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False])

In [124]:
(x % 3 == 0) & (x % 4 == 1)

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False])

### 배열 인덱싱

넘파이 배열 객체의 또다른 강력한 기능은 팬시 인덱싱(fancy indexing)이라고도 부르는 배열 인덱싱(array indexing) 방법이다.

In [126]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [127]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [129]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [130]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [131]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [133]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [135]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

### 연습문제 3

다음 행렬과 같은 배열이 있다.
```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```
1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [137]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [139]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [140]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [141]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])