# 3.3 배열의 연산

### 벡터화 연산

In [4]:
import numpy as np

In [5]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [14]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 6 ms


In [15]:
%%time
z = x + y

Wall time: 0 ns


In [16]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

사칙 연산뿐 아니라 비교 연산과 같은 논리 연산도 벡터화 연산이 가능하다.

In [18]:
a == b

array([False,  True, False,  True])

In [19]:
a >= b

array([False,  True,  True,  True])

만약 배열의 각 원소들을 일일히 비교하는 것이 아니라 배열의 모든 원소가 다 같은지 알고 싶다면 all 명령을 사용하면 된다.

In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [21]:
np.all(a == b)

False

In [22]:
np.all(a == c)

True

지수 함수, 로그 함수 등의 수학 함수도 벡터화 연산을 지원한다.

In [25]:
a = np.arange(5)

In [28]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [26]:
# 자연로그
np.log(a)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [27]:
# 상용로그
np.log10(a)

array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999])

In [29]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### 스칼라와 벡터/행렬의 곱셈

스칼라와 벡터/행렬의 곱도 선형 대수에서 사용하는 식과 넘파이 코드가 일치한다.

In [31]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [34]:
x = np.arange(12).reshape(3, 4)
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

### 브로드캐스팅

벡터(또는 행렬)끼리 덧셈 혹은 뺄셈을 하려면 두 벡터(또는 행렬)의 크기가 같아야 한다. 넘파이에서는 서로 다른 크기를 가진 두 배열의 사칙 연산도 지원한다. 이 기능을 브로드캐스팅(broadcasting)이라고 하는데 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방벙이다.

In [36]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [37]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [38]:
x + y

array([1, 2, 3, 4, 5])

In [39]:
x + 1

array([1, 2, 3, 4, 5])

### 차원 축소 연산

- 최대/최소: min, max, argmin, argmax
- 통계: sum, mean, median, std, var
- 불리언: all, any

In [4]:
import numpy as np

In [6]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [7]:
np.sum(x)

6

In [8]:
np.sum(x, axis=0)

array([3, 3])

In [9]:
np.sum(x, axis=1)

array([2, 4])

### 연습 문제 3.3.1

실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

- 전체의 최댓값
- 각 행의 합
- 각 행의 최댓값
- 각 열의 평균
- 각 열의 최솟값

In [13]:
x = np.linspace(1.0, 10.0, 30).reshape(5, 6)
x

array([[ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
         2.55172414],
       [ 2.86206897,  3.17241379,  3.48275862,  3.79310345,  4.10344828,
         4.4137931 ],
       [ 4.72413793,  5.03448276,  5.34482759,  5.65517241,  5.96551724,
         6.27586207],
       [ 6.5862069 ,  6.89655172,  7.20689655,  7.51724138,  7.82758621,
         8.13793103],
       [ 8.44827586,  8.75862069,  9.06896552,  9.37931034,  9.68965517,
        10.        ]])

In [25]:
# 전체의 최댓값
x.max(), np.max(x)

(10.0, 10.0)

In [28]:
# 각 행의 합
x.sum(), np.sum(x)

(165.0, 165.0)

In [18]:
# 각 행의 최댓값
x.max(axis=1)

array([ 2.55172414,  4.4137931 ,  6.27586207,  8.13793103, 10.        ])

In [20]:
x.sum(axis=0)

array([23.62068966, 25.17241379, 26.72413793, 28.27586207, 29.82758621,
       31.37931034])

In [30]:
x.sum(axis=0)

array([23.62068966, 25.17241379, 26.72413793, 28.27586207, 29.82758621,
       31.37931034])

In [31]:
x.min(axis=0)

array([1.        , 1.31034483, 1.62068966, 1.93103448, 2.24137931,
       2.55172414])

### 정렬

sort 함수나 메서드를 사용하여 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열을 만들 수도 있다. 2차원 이상인 경우에는 행이나 열을 각각 따로따로 정렬하는데 axis 인수를 사용하여 행을 정렬할 것인지 열을 정렬한 것인지 결정한다. axis=0이면 각각의 행을 따로따로 정렬하고 axis=1이면 각각의 열을 따로따로 정렬한다. 디폴트 값은 -1 즉 가장 안쪽(나중)의 차원이다.

In [33]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [39]:
np.sort(a), np.sort(a, axis=1)

(array([[ 3,  4,  5,  7],
        [ 1,  9, 11, 12],
        [ 1,  2, 14, 15]]),
 array([[ 3,  4,  5,  7],
        [ 1,  9, 11, 12],
        [ 1,  2, 14, 15]]))

In [36]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [40]:
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

sort 메서드는 해당 객체의 자료 자체가 변화하는 자체변화(in-place) 메서드이므로 사용할 때 주의를 기울여야 한다.

In [41]:
a.sort()

In [42]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

만약 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort 명령을 사용한다.

In [44]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)