# 2.2 벡터와 행렬의 연산

### 벡터와 벡터의 곱셈

벡터의 내적 inner product, dot product

In [111]:
import numpy as np
import matplotlib.pylab as plt

In [112]:
x = np.arange(1, 4).reshape(3, 1)
x

array([[1],
       [2],
       [3]])

In [113]:
y = np.arange(4, 7).reshape(3, 1)
y

array([[4],
       [5],
       [6]])

In [114]:
# 벡터의 내적은 n의 값이 같아야 할수 있다.
# ((3, n), (n, 1))
x.shape, y.shape

((3, 1), (3, 1))

In [115]:
# x 의 행과 열의 바꾸어 n 값을 3으로 바꾼다.
x.T.shape

(1, 3)

In [116]:
z = x.T @ y
z

array([[32]])

In [117]:
z.shape

(1, 1)

In [118]:
z[0, 0]

32

In [119]:
np.dot(x.T, y)

array([[32]])

In [120]:
x = np.arange(1,7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
x @ x.T

array([[14, 32],
       [32, 77]])

In [122]:
def mat_mul(x, y):
    z = np.zeros((len(x), len(y[0])))
    if len(x[0]) != len(y):
        return z
    for i in range(len(x)):
        for m in range(len(y[0])):
            v = 0
            for k in range(len(x[0])):
                v += x[i, k] * y[k, m]
            z[i, m] = v
    return z

In [123]:
x = np.arange(1, 7).reshape(3, 2)
y = x.T
mat_mul(x, y)

array([[ 5., 11., 17.],
       [11., 25., 39.],
       [17., 39., 61.]])

In [124]:
np.dot(x, y)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [125]:
x @ x.T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

### 가중합

벡터의 내적은 가중합을 계산할 때 쓰일 수 있다. **가중합(weighted sum)**이란 복수의 데이터를 단순히 합하는 것이 아니라 각각의 수에 어떤 가중치 값을 곱한 후 이 곱셈 결과들을 다시 합한 것을 말한다.

### 연습 문제 2.2.1

A, B, C 세 회사의 주식은 각각 100만원, 80만원, 50만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할 때 필요한 금액을 구하고자 한다.

1. 주식의 가격과 수량을 각각 p 벡터, n 벡터로 표시하고 넘파이로 코딩한다.
2. 주식을 매수할 때 필요한 금액을 곱셈으로 표시하고 넘파이 연산으로 그 값을 계산한다.

In [126]:
p = np.array([100, 80, 50]) * 10000
n = p.reshape(1, 3)

In [127]:
n = np.array([3, 4, 5]).reshape(3, 1)

In [129]:
# money = (p @ n)[0, 0]
money

array([8700000])

# 연습 문제 2.2.4

(1) A와 B가 위와 같을 때 AB를 연습장에 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다.

In [131]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])

In [133]:
A.shape, B.shape

((2, 3), (3, 2))

In [135]:
A @ B

array([[22, 28],
       [49, 64]])

(2) 순서를 바꾸어 BA를 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. BA가 AB와 같은가?

In [138]:
B.shape, A.shape

((3, 2), (2, 3))

In [137]:
B @ A

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

(3) A, B가 다음과 같을 때, AB, BA를 (계산이 가능하다면) 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. AB, BA 모두 계산 가능한가?

In [166]:
A = np.arange(1, 4)
B = np.arange(4, 10).reshape(3, 2)

print(A)
print(B)

[1 2 3]
[[4 5]
 [6 7]
 [8 9]]


In [167]:
print(A.shape, B.shape)
A @ B

(3,) (3, 2)


array([40, 46])

In [162]:
print(B.shape, A.shape)
B @ A

(3, 2) (3,)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

(4) A, B가 다음과 같을 때, AB, BA를 (계산이 가능하다면) 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. AB, BA 모두 계산 가능한가? BA의 결과가 AB와 같은가?

In [159]:
A = np.arange(1, 5).reshape(2, 2)
B = np.arange(5, 9).reshape(2, 2)

print(A.shape, B.shape)
A @ B

(2, 2) (2, 2)


array([[19, 22],
       [43, 50]])

In [160]:
print(B.shape, A.shape)
B @ A

(2, 2) (2, 2)


array([[23, 34],
       [31, 46]])